api_platform:
    title: DBJR Internal Time Tracking API
    version: 0.1.0
    mapping:
        paths:
            - '%kernel.project_dir%/config/api'
    formats:
        json:
            mime_types:
                - 'application/json'
        html:
            mime_types:
                - 'text/html'
    collection:
        pagination:
            enabled: false
