parameters:
    # Adds a fallback DATABASE_URL and DATABASE_URL if the env var is not set.
    env(DATABASE_URL): 'postgresql://postgres:pass@db/docker?serverVersion=11&charset=utf8'
    env(DATABASE_URL_TEST): 'postgresql://postgres:pass@db/docker_test?serverVersion=11&charset=utf8'

doctrine:
    dbal:
        driver: pdo_pgsql
        server_version: 11.7
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: yml
                dir: '%kernel.project_dir%/config/doctrine'
                is_bundle: false
                prefix: 'App\Entity'
        dql:
            string_functions:
                overlaps: App\DQL\OverlapsFunction
