parameters:
    # Adds a fallback CORS_ALLOW_ORIGIN if the env var is not set.
    env(CORS_ALLOW_ORIGIN): '^https?://localhost:?[0-9]*$'

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '%env(CORS_ALLOW_ORIGIN)%'
        allow_methods:
            - 'GET'
            - 'OPTIONS'
            - 'POST'
            - 'PUT'
            - 'PATCH'
            - 'DELETE'
        allow_headers:
            - 'Content-Type'
            - 'Authorization'
        expose_headers:
            - 'Link'
        max_age: 3600
    paths:
        '^/': ~