security:
    providers:
        webservice:
            id: App\Security\User\UserProvider
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        !php/const App\Entity\User::ROLE_USER: ~
        !php/const App\Entity\User::ROLE_EMPLOYEE: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_ADMIN: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_SUPER_ADMIN: !php/const App\Entity\User::ROLE_ADMIN

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        -   path: '^/users/[0-9]+/supervised_users$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/work_hours$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        - { path: '^/users/[0-9]+/work_logs$', roles: !php/const App\Entity\User::ROLE_EMPLOYEE }
        - { path: ^/users, roles: !php/const App\Entity\User::ROLE_ADMIN }
        - { path: ^/work_hours, roles: !php/const App\Entity\User::ROLE_EMPLOYEE }
        - { path: ^/work_logs, roles: !php/const App\Entity\User::ROLE_EMPLOYEE }
        -   path: ^/logout,
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
