security:
    providers:
        webservice:
            id: App\Security\User\UserProvider
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        !php/const App\Entity\User::ROLE_USER: ~
        !php/const App\Entity\User::ROLE_EMPLOYEE: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_ADMIN: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_SUPER_ADMIN: !php/const App\Entity\User::ROLE_ADMIN

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        -   path: ^/business_trip_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/home_office_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/overtime_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/sick_day_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/special_approvals/[0-9]+'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_SUPER_ADMIN
        -   path: ^/time_off_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/supervised_users$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/vacation_work_logs
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/work_hours$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+$'
            methods: [GET]
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: '^/users/[0-9]+/work_months$'
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        - { path: ^/users, roles: !php/const App\Entity\User::ROLE_ADMIN }
        - { path: ^/work_hours, roles: !php/const App\Entity\User::ROLE_EMPLOYEE }
        - { path: ^/work_logs, roles: !php/const App\Entity\User::ROLE_EMPLOYEE }
        -   path: ^/work_months
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
        -   path: ^/logout,
            roles:
                - !php/const App\Entity\User::ROLE_EMPLOYEE
                - !php/const App\Entity\User::ROLE_ADMIN
