web:
    image: visionappscz/apache-php:7.2
    links:
        - db
    volumes:
        - .:/www
db:
    image: postgres:9.4
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass
