apache:
    build: docker/Apache
    volumes:
        - .:/www
    links:
        - php
    ports:
        - 80:80

php:
    build: docker/PHP
    volumes:
        - .:/www
    working_dir: /www
    links:
        - db
        - mail

tools:
    build: docker/Tools
    volumes:
        - .:/www
    working_dir: /www
    links:
        - db

db:
    image: postgres:9.4
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: pass

adminer:
    image: clue/adminer
    links:
        - db
    ports:
        - 81:80

mail:
    image: mailhog/mailhog
    ports:
        - 82:8025
