App\Entity\Config:
    attributes:
        id:
            groups:
                - config_out
                - config_in
        supportedHolidays:
            groups:
                - config_out
                - config_in
        supportedYears:
            groups:
                - config_out
                - config_in
        workedHoursLimits:
            groups:
                - config_out
