App\Entity\Config:
    attributes:
        supportedHolidays:
            groups:
                - config_out
        supportedYears:
            groups:
                - config_out
        workedHoursLimits:
            groups:
                - config_out
