App\Entity\MaternityProtectionWorkLog:
    attributes:
        id:
            groups:
                - maternity_protection_work_log_out_detail
                - work_month_out_detail
        date:
            groups:
                - maternity_protection_work_log_out_detail
                - work_month_out_detail
                - maternity_protection_work_log_in
        workMonth:
            groups:
                - maternity_protection_work_log_out_detail
                - maternity_protection_work_log_in
