App\Entity\ParentalLeaveWorkLog:
    attributes:
        id:
            groups:
                - parental_leave_work_log_out_detail
                - work_month_out_detail
        date:
            groups:
                - parental_leave_work_log_out_detail
                - work_month_out_detail
                - parental_leave_work_log_in
        workMonth:
            groups:
                - parental_leave_work_log_out_detail
                - parental_leave_work_log_in
