App\Entity\SupportedYear:
    attributes:
        year:
            groups:
                - config_out
                - special_approvals_out_list
                - supervised_user_out_list
                - supported_year_out_detail
                - supported_year_out_list
                - supported_year_out_in
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - vacation_out_list
                - vacation_out_detail
                - work_hours_out_list
                - work_hours_out_detail
                - work_month_out_list
                - work_month_out_detail
                - config_in
                - vacation_in
                - work_hours_in
