App\Entity\TrainingWorkLogSupport:
    attributes:
        id:
            groups:
                - training_work_log_out_detail
                - training_work_log_support_out_detail
                - special_approvals_out_list

        dateTime:
            groups:
                - training_work_log_out_detail
                - training_work_log_support_out_detail
                - special_approvals_out_list

        supportedBy:
            groups:
                - training_work_log_out_detail
                - training_work_log_support_out_detail
                - special_approvals_out_list

        workLog:
            groups:
                - training_work_log_support_out_detail
                - training_work_log_support_in
