App\Entity\User:
    attributes:
        id:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - work_month_out_list
                - work_month_out_detail
        email:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - user_in
        employeeId:
            groups:
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - user_in
        firstName:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        lastName:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - special_approvals_out_list
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        plainPassword:
            groups:
                - user_in
        isActive:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        roles:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        supervisor:
            groups:
                - special_approvals_out_list
                - supervised_user_out_list
                - user_out_list
                - user_out_detail
                - user_in
        allSupervisors:
            groups:
                - special_approvals_out_list
                - user_out_list
                - user_out_detail
                - user_in
        vacations:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - work_month_out_detail
                - user_in
        workHours:
            groups:
                - user_out_list
                - user_out_detail
                - user_out_api_token_detail
                - supervised_user_out_list
                - user_in
        workMonths:
            groups:
                - supervised_user_out_list
        yearStats:
            groups:
                - user_out_detail
                - user_out_list
                - work_month_out_detail
        notifications:
            groups:
                - user_out_detail
                - user_in
        apiToken:
            groups:
                - user_out_detail
                - user_out_api_token_detail
