App\Entity\User:
    attributes:
        id:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - work_month_out_list
                - work_month_out_detail
        email:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - user_in
        firstName:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - user_in
        lastName:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - user_in
        plainPassword:
            groups:
                - user_in
        isActive:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - user_in
        roles:
            groups:
                - user_out_list
                - user_out_detail
                - supervised_user_out_list
                - user_in
        supervisor:
            groups:
                - user_out_list
                - user_out_detail
                - user_in
        workHours:
            groups:
                - user_out_list
                - user_in