App\Entity\WorkMonth:
    attributes:
        id:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - business_trip_work_log_out_detail
                - home_office_work_log_out_detail
                - time_off_work_log_out_detail
                - work_log_out_detail
                - supervised_user_out_list
        year:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - supervised_user_out_list
        month:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - supervised_user_out_list
        status:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - supervised_user_out_list
        user:
            groups:
                - work_month_out_list
                - work_month_out_detail
        businessTripWorkLogs:
            groups:
                - work_month_out_detail
        homeOfficeWorkLogs:
            groups:
                - work_month_out_detail
        timeOffWorkLogs:
            groups:
                - work_month_out_detail
        workLogs:
            groups:
                - work_month_out_detail