App\Entity\WorkMonth:
    attributes:
        id:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - business_trip_work_log_out_detail
                - home_office_work_log_out_detail
                - overtime_work_log_out_detail
                - sick_day_work_log_out_detail
                - special_approvals_out_list
                - time_off_work_log_out_detail
                - vacation_work_log_out_detail
                - work_log_out_detail
                - supervised_user_out_list
        year:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - special_approvals_out_list
                - supervised_user_out_list
        month:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - special_approvals_out_list
                - supervised_user_out_list
        status:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - special_approvals_out_list
                - supervised_user_out_list
        user:
            groups:
                - work_month_out_list
                - work_month_out_detail
                - special_approvals_out_list
        businessTripWorkLogs:
            groups:
                - work_month_out_detail
        homeOfficeWorkLogs:
            groups:
                - work_month_out_detail
        maternityProtectionWorkLogs:
            groups:
                - work_month_out_detail
        overtimeWorkLogs:
            groups:
                - work_month_out_detail
        parentalLeaveWorkLogs:
            groups:
                - work_month_out_detail
        sickDayWorkLogs:
            groups:
                - work_month_out_detail
        timeOffWorkLogs:
            groups:
                - work_month_out_detail
        vacationWorkLogs:
            groups:
                - work_month_out_detail
        workLogs:
            groups:
                - work_month_out_detail
