App\Entity\WorkLog:
    attributes:
        id:
            groups:
                - work_log_out_detail
                - work_month_out_detail
        startTime:
            groups:
                - work_log_out_detail
                - work_month_out_detail
                - work_log_in
        endTime:
            groups:
                - work_log_out_detail
                - work_month_out_detail
                - work_log_in
        workMonth:
            groups:
                - work_log_out_detail
