#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login:
    path: /login
    methods: [POST]

api_logout:
    path: /logout
    methods: [POST]

api_login_check:
    path: /login_check
    methods: [POST]
