#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /login_check
    methods: [POST]

api_logout:
    path: /logout
    methods: [POST]

api_supervised_users:
    path: /users/{id}/supervised_users
    methods: ['GET']
    controller: App\Controller\UserController:supervisedUsers
    defaults:
        _api_collection_operation_name: 'supervisedUsers'