#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
    path: /login_check
    methods: [POST]

api_logout:
    path: /logout
    methods: [POST]

api_business_trip_work_log_mark_approved:
    path: /business_trip_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\BusinessTripWorkLogController:markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_business_trip_work_log_mark_rejected:
    path: /business_trip_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\BusinessTripWorkLogController:markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_home_office_work_log_mark_approved:
    path: /home_office_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\HomeOfficeWorkLogController:markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_home_office_work_log_mark_rejected:
    path: /home_office_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\HomeOfficeWorkLogController:markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_time_off_work_log_mark_approved:
    path: /time_off_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\TimeOffWorkLogController:markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_time_off_work_log_mark_rejected:
    path: /time_off_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\TimeOffWorkLogController:markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_vacation_work_log_mark_approved:
    path: /vacation_work_logs/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController:markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_vacation_work_log_mark_rejected:
    path: /vacation_work_logs/{id}/mark_rejected
    methods: [PUT]
    controller: App\Controller\VacationWorkLogController:markRejected
    defaults:
        _api_collection_operation_name: 'markRejected'

api_supervised_users:
    path: /users/{id}/supervised_users
    methods: [GET]
    controller: App\Controller\UserController:supervisedUsers
    defaults:
        _api_collection_operation_name: 'supervisedUsers'

api_work_months_special_approvals:
    path: /special_approvals/{supervisorId}
    methods: [GET]
    controller: App\Controller\WorkMonthController:specialApprovals
    defaults:
        _api_collection_operation_name: 'specialApprovals'

api_work_months_mark_approved:
    path: /work_months/{id}/mark_approved
    methods: [PUT]
    controller: App\Controller\WorkMonthController:markApproved
    defaults:
        _api_collection_operation_name: 'markApproved'

api_work_months_mark_waiting_for_approval:
    path: /work_months/{id}/mark_waiting_for_approval
    methods: [PUT]
    controller: App\Controller\WorkMonthController:markWaitingForApproval
    defaults:
        _api_collection_operation_name: 'markWaitingForApproval'

