App\Entity\BanWorkLog:
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        workTimeLimit:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: 0
                max: 86400

        workMonth:
            - NotBlank: ~
