App\Entity\BusinessTripWorkLog:
    properties:
        date:
            - NotBlank: ~
            - DateTime: ~

        purpose:
            - NotBlank: ~

        destination:
            - NotBlank: ~

        transport:
            - NotBlank: ~

        expectedDeparture:
            - NotBlank: ~

        expectedArrival:
            - NotBlank: ~

        timeApproved:
            - DateTime: ~

        timeRejected:
            - DateTime: ~

        workMonth:
            - NotBlank: ~