App\Entity\BusinessTripWorkLog:
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        purpose:
            - NotBlank: ~

        destination:
            - NotBlank: ~

        transport:
            - NotBlank: ~

        expectedDeparture:
            - NotBlank: ~

        expectedArrival:
            - NotBlank: ~

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
