App\Entity\HomeOfficeWorkLog:
    properties:
        date:
            - NotBlank: ~
            - DateTime: ~

        comment:
            - NotBlank: ~

        timeApproved:
            - DateTime: ~

        timeRejected:
            - DateTime: ~

        workMonth:
            - NotBlank: ~