App\Entity\HomeOfficeWorkLog:
    constraints:
        -   App\Validator\Constraints\WorkLogWithinValidContract: ~
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        plannedEndHour:
            - NotBlank: ~
            - Type: numeric
            - Range:
                  min: 0
                  max: 23

        plannedEndMinute:
            - NotBlank: ~
            - Type: numeric
            - Range:
                  min: 0
                  max: 59

        plannedStartHour:
            - NotBlank: ~
            - Type: numeric
            - Range:
                  min: 0
                  max: 23

        plannedStartMinute:
            - NotBlank: ~
            - Type: numeric
            - Range:
                  min: 0
                  max: 59

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
