App\Entity\HomeOfficeWorkLog:
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
