App\Entity\MaternityProtectionWorkLog:
    constraints:
        -   App\Validator\Constraints\WorkLogWithinValidContract: ~
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
