App\Entity\OvertimeWorkLog:
    properties:
        date:
            - NotBlank: ~
            - DateTime: ~

        reason:
            - NotBlank: ~

        timeApproved:
            - DateTime: ~

        timeRejected:
            - DateTime: ~

        workMonth:
            - NotBlank: ~