App\Entity\OvertimeWorkLog:
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        reason:
            - NotBlank: ~

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
