App\Entity\SickDayWorkLog:
    constraints:
        - App\Validator\Constraints\SickDayWorkLogValid: ~
        - App\Validator\Constraints\WorkLogWithinValidContract: ~
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        childDateOfBirth:
            - Type: DateTimeImmutable

        variant:
            - NotBlank: ~
            - Choice:
                callback: getConstantVariants

        workMonth:
            - NotBlank: ~
