App\Entity\TimeOffWorkLog:
    constraints:
        -   App\Validator\Constraints\WorkLogWithinValidContract: ~
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
