App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        email:
            - NotBlank: ~
            - Email:
                strict: true

        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

        plainPassword:
            - NotBlank:
                groups:
                    - user_password_required
            - Length:
                min: 8
