App\Entity\User:
    properties:
        email:
            - NotBlank: ~
            - Email:
                checkMX: true
                strict: true

        firstName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

        lastName:
            - NotBlank: ~
            - Length:
                min: 2
                max: 200

