App\Entity\UserNotifications:
    properties:
        supervisorInfoMondayTime:
            - Type: DateTimeImmutable
        supervisorInfoTuesdayTime:
            - Type: DateTimeImmutable
        supervisorInfoWednesdayTime:
            - Type: DateTimeImmutable
        supervisorInfoThursdayTime:
            - Type: DateTimeImmutable
        supervisorInfoFridayTime:
            - Type: DateTimeImmutable
        supervisorInfoSaturdayTime:
            - Type: DateTimeImmutable
        supervisorInfoSundayTime:
            - Type: DateTimeImmutable
        supervisorInfoSendOnHolidays:
            - NotNull: ~
