App\Entity\VacationWorkLog:
    constraints:
        - App\Validator\Constraints\VacationDaysNotExhausted: ~

    properties:
        date:
            - NotBlank: ~
            - DateTime: ~

        timeApproved:
            - DateTime: ~

        timeRejected:
            - DateTime: ~

        workMonth:
            - NotBlank: ~