App\Entity\VacationWorkLog:
    constraints:
        - App\Validator\Constraints\VacationDaysNotExhausted: ~

    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
