App\Entity\VacationWorkLog:
    properties:
        date:
            - NotBlank: ~
            - DateTime: ~

        timeApproved:
            - DateTime: ~

        timeRejected:
            - DateTime: ~

        workMonth:
            - NotBlank: ~