App\Entity\Vacation:
    properties:
        user:
            - NotBlank: ~

        year:
            - NotBlank: ~
            - Valid: ~

        vacationDays:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: 0
                max: 365

        vacationDaysCorrection:
            - NotBlank: ~
            - Type: numeric
            - Range:
                min: -365
                max: 365
