App\Entity\VacationWorkLog:
    constraints:
        - App\Validator\Constraints\VacationDaysNotExhausted: ~
        - App\Validator\Constraints\WorkLogWithinValidContract: ~
    properties:
        date:
            - NotBlank: ~
            - Type: DateTimeImmutable

        timeApproved:
            - Type: DateTimeImmutable

        timeRejected:
            - Type: DateTimeImmutable

        workMonth:
            - NotBlank: ~
