App\Entity\WorkMonth:
    properties:
        month:
            - NotBlank: ~
            - Range:
                min: 1
                max: 12
        year:
            - Valid: ~
        status:
            - NotBlank: ~
            - Choice:
                callback: getConstantStatuses
        user:
            - NotBlank: ~
        requiredTime:
            - Type: numeric
        workedTime:
            - Type: numeric
        workTimeCorrection:
            - NotBlank: ~
            - Type: numeric
