App\Entity\WorkLog:
    constraints:
        - App\Validator\Constraints\TimeIntervalNotOverlaps: ~

    properties:
        startTime:
            - NotBlank: ~
            - Type: DateTimeImmutable

        endTime:
            - NotBlank: ~
            - Type: DateTimeImmutable
            - GreaterThan:
                propertyPath: startTime

        workMonth:
            - NotBlank: ~
