App\Entity\WorkLog:
    constraints:
        - App\Validator\Constraints\TimeIntervalNotOverlaps: ~

    properties:
        startTime:
            - NotBlank: ~
            - DateTime: ~

        endTime:
            - NotBlank: ~
            - DateTime: ~
            - GreaterThan:
                propertyPath: startTime
