App\Entity\BusinessTripWorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        date:
            type: datetime_immutable
        timeApproved:
            type: datetime_immutable
            nullable: true
        timeRejected:
            type: datetime_immutable
            nullable: true

    manyToOne:
        workMonth:
            targetEntity: App\Entity\WorkMonth
            inversedBy: businessTripWorkLogs
            joinColumn:
                name: work_month_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade
