App\Entity\Config:
    type: entity
    repositoryClass: App\Repository\ConfigRepository

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        title:
            type: text
            unique: true
        description:
            type: text
            nullable: true
