App\Entity\User:
    type: entity
    table: app_user

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        email:
            type: text
            unique: true

        firstName:
            type: text

        lastName:
            type: text

        password:
            type: text

        roles:
            type: json_array

    oneToMany:
        workLogs:
            targetEntity: App\Entity\WorkLog
            mappedBy: user
