App\Entity\UserYearStats:
    type: entity
    table: app_user_year_stats

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    indexes:
        year_user_idx:
            columns: [year, user_id]
            type: unique
        year_idx:
            columns: [year]

    fields:
        year:
            type: integer
            index:
        requiredHours:
            type: float
        workedHours:
            type: float
        vacationDaysUsed:
            type: integer

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: yearStats
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
