App\Entity\WorkHours:
    type: entity

    id:
        month:
            type: integer
        user:
            associationKey: true
        year:
            type: integer

    fields:
        requiredHours:
            type: float

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: workHours
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade
