App\Entity\WorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        startTime:
            type: datetime_immutable
        endTime:
            type: datetime_immutable

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: workLogs
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade
