App\Entity\WorkMonth:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        month:
            type: integer
        year:
            type: integer
        status:
            type: text

    oneToMany:
        businessTripWorkLogs:
            targetEntity: App\Entity\BusinessTripWorkLog
            mappedBy: workMonth
        homeOfficeWorkLogs:
            targetEntity: App\Entity\HomeOfficeWorkLog
            mappedBy: workMonth
        timeOffWorkLogs:
            targetEntity: App\Entity\TimeOffWorkLog
            mappedBy: workMonth
        workLogs:
            targetEntity: App\Entity\WorkLog
            mappedBy: workMonth

    manyToOne:
        user:
            targetEntity: App\Entity\User
            inversedBy: workMonths
            joinColumn:
                name: user_id
                referencedColumnName: id
                nullable: false
                onDelete: cascade

    uniqueConstraints:
        work_month_idx:
            columns:
                - month
                - user_id
                - year