App\Entity\WorkLog:
    type: entity

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        startTime:
            type: datetime_immutable
        endTime:
            type: datetime_immutable
        isHomeOffice:
            type: boolean

    manyToOne:
        workMonth:
            targetEntity: App\Entity\WorkMonth
            inversedBy: workLogs
            joinColumn:
                name: work_month_id
                referencedColumnName: id
                nullable: false
