App\Entity\BusinessTripWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - business_trip_work_log_out_detail
            denormalization_context:
                groups:
                    - business_trip_work_log_in
    itemOperations:
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - business_trip_work_log_out_detail
