App\Entity\Config:
    collectionOperations:
        get:
            method: 'GET'
            normalization_context:
                groups:
                    - config_out_list
        post:
            method: 'POST'
            normalization_context:
                groups:
                    - config_out_detail
            denormalization_context:
                groups:
                    - config_in
    itemOperations:
        delete:
            method: 'DELETE'
        get:
            method: 'GET'
            normalization_context:
                groups:
                    - config_out_detail
        put:
            method: 'PUT'
            normalization_context:
                groups:
                    - config_out_detail
            denormalization_context:
                groups:
                    - config_in