App\Entity\Config:
    properties:
        id:
            identifier: true
    collectionOperations:
        getConfig:
            method: GET
            route_name: api_config_get
            normalization_context:
                groups:
                    - config_out
        post:
            method: POST
            route_name: api_config_save
            normalization_context:
                groups:
                    - config_out
            denormalization_context:
                groups:
                    - config_in
    itemOperations:
        get:
            controller: 'NotFoundAction::class'
            read: false
            output: false
