App\Entity\Contract:
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - contract_out_list
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - contract_out_detail
        makeContractPermanent:
            method: PUT
            route_name: api_contract_make_contract_permanent
            normalization_context:
                groups:
                    - contract_out_detail
            swagger_context:
                summary: Make Contract permanent.
        terminateContract:
            method: PUT
            route_name: api_contract_terminate_contract
            normalization_context:
                groups:
                    - contract_out_detail
            swagger_context:
                summary: Terminate Contract.
                parameters:
                    -   name: dateTime
                        description: 'Date time of termination'
                        type: int
                        in: body
                        required: true
    subresourceOperations:
        api_user_contacts_get_subresource:
            method: GET
            normalization_context:
                groups:
                    - contract_out_list
