App\Entity\OvertimeWorkLogSupport:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - overtime_work_log_support_out_detail
            denormalization_context:
                groups:
                    - overtime_work_log_support_in
        bulkCreate:
            method: POST
            route_name: api_overtime_work_log_support_bulk_create
            swagger_context:
                summary: Creates multiple OvertimeWorkLogSupport resource.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - overtime_work_log_support_out_detail
