App\Entity\SickDayWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - sick_day_work_log_out_detail
            denormalization_context:
                groups:
                    - sick_day_work_log_in
        bulkCreate:
            method: POST
            route_name: api_sick_day_work_log_bulk_create
            swagger_context:
                summary: Creates multiple SickDayWorkLog resources.
    itemOperations:
        put:
            method: PUT
            normalization_context:
                groups:
                    - sick_day_work_log_out_detail
            denormalization_context:
                groups:
                    - sick_day_work_log_in
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - sick_day_work_log_out_detail
