App\Entity\SickDayUnpaidWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - sick_day_unpaid_work_log_out_detail
            denormalization_context:
                groups:
                    - sick_day_unpaid_work_log_in
        bulkCreate:
            method: POST
            route_name: api_sick_day_unpaid_work_log_bulk_create
            swagger_context:
                summary: Creates multiple SickDayUnpaidWorkLog resources.
    itemOperations:
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - sick_day_unpaid_work_log_out_detail
