App\Entity\TimeOffWorkLogSupport:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - time_off_work_log_support_out_detail
            denormalization_context:
                groups:
                    - time_off_work_log_support_in
        bulkCreate:
            method: POST
            route_name: api_time_off_work_log_support_bulk_create
            swagger_context:
                summary: Creates multiple TimeOffWorkLogSupport resource.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - time_off_work_log_support_out_detail
