App\Entity\TimeOffWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            denormalization_context:
                groups:
                    - time_off_work_log_in
        bulkCreate:
            method: POST
            route_name: api_time_off_work_log_bulk_create
            swagger_context:
                summary: Creates multiple TimeOffWorkLog resources.
    itemOperations:
        put:
            method: PUT
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            denormalization_context:
                groups:
                    - time_off_work_log_in
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
        bulkMarkApproved:
            method: PUT
            route_name: api_time_off_work_log_bulk_mark_approved
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks multiple TimeOffWorkLog resources as approved.
                parameters:
                    - name: workLogIds
                      description: 'Work log ids'
                      type: array
                      in: body
                      required: true
        bulkMarkRejected:
            method: PUT
            route_name: api_time_off_work_log_bulk_mark_rejected
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks multiple TimeOffWorkLog resources as rejected.
                parameters:
                    - name: workLogIds
                      description: 'Work log ids'
                      type: array
                      in: body
                      required: true
                    - name: rejectionMessage
                      description: 'Rejection message'
                      type: string
                      in: body
                      required: true
        markApproved:
            method: PUT
            route_name: api_time_off_work_log_mark_approved
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks the TimeOffWorkLog as approved.
        markRejected:
            method: PUT
            route_name: api_time_off_work_log_mark_rejected
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks the TimeOffWorkLog as rejected.

