App\Entity\TimeOffWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            denormalization_context:
                groups:
                    - time_off_work_log_in
    itemOperations:
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
        markApproved:
            method: PUT
            route_name: api_time_off_work_log_mark_approved
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks the TimeOffWorkLog as approved.
        markRejected:
            method: PUT
            route_name: api_time_off_work_log_mark_rejected
            normalization_context:
                groups:
                    - time_off_work_log_out_detail
            swagger_context:
                summary: Marks the TimeOffWorkLog as rejected.

