App\Entity\User:
    properties:
        workHours:
            subresource:
                resourceClass: 'App\Entity\WorkHours'
                collection: true
        workLogs:
            subresource:
                resourceClass: 'App\Entity\WorkLog'
                collection: true
    collectionOperations:
        supervisedUsers:
            method: 'GET'
            route_name: 'api_supervised_users'
            filters:
                - 'order_filter.supervised_user'
            normalization_context:
                groups:
                    - supervised_user_out_list
        get:
            method: 'GET'
            filters:
                - 'order_filter.user'
            normalization_context:
                groups:
                    - user_out_list
                    - work_hours_out_list
        post:
            method: 'POST'
            normalization_context:
                groups:
                    - user_out_detail
            denormalization_context:
                groups:
                    - user_in
                    - work_hours_in
            validation_groups:
                - User
                - user_password_required
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups:
                    - user_out_detail
        put:
            method: 'PUT'
            normalization_context:
                groups:
                    - user_out_detail
            denormalization_context:
                groups:
                    - user_in
                    - work_hours_in
        delete:
            method: 'DELETE'
        login_check:
            method: 'POST'
            route_name: 'api_login_check'
            swagger_context:
                summary: 'Authenticate user.'
                responses:
                    200:
                        description: 'User was logged in.'
                    401:
                        description: 'Bad Credentials.'
                    400:
                        description: 'Invalid request.'
                parameters:
                    - name: email
                      description: 'Email'
                      type: string
                      in: body
                      required: true
                    - name: password
                      description: 'Password'
                      type: string
                      in: body
                      required: true
        logout:
            method: 'POST'
            route_name: 'api_logout'
            swagger_context:
                summary: 'Log out user.'
                responses:
                    200:
                        description: 'User was logged out.'
                    401:
                        description: 'Bad Credentials.'
                    400:
                        description: 'Invalid request.'
                parameters: ~
