App\Entity\VacationWorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - vacation_work_log_out_detail
            denormalization_context:
                groups:
                    - vacation_work_log_in
        bulkCreate:
            method: POST
            route_name: api_vacation_work_log_bulk_create
            swagger_context:
                summary: Creates multiple VacationWorkLog resource.
    itemOperations:
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - vacation_work_log_out_detail
        bulkMarkApproved:
            method: PUT
            route_name: api_vacation_work_log_bulk_mark_approved
            normalization_context:
                groups:
                - vacation_work_log_out_detail
            swagger_context:
                summary: Marks multiple VacationWorkLog resources as approved.
                parameters:
                - name: workLogIds
                  description: 'Work log ids'
                  type: array
                  in: body
                  required: true
        bulkMarkRejected:
            method: PUT
            route_name: api_vacation_work_log_bulk_mark_rejected
            normalization_context:
                groups:
                - vacation_work_log_out_detail
            swagger_context:
                summary: Marks multiple VacationWorkLog resources as rejected.
                parameters:
                - name: workLogIds
                  description: 'Work log ids'
                  type: array
                  in: body
                  required: true
                - name: rejectionMessage
                  description: 'Rejection message'
                  type: string
                  in: body
                  required: true
        markApproved:
            method: PUT
            route_name: api_vacation_work_log_mark_approved
            normalization_context:
                groups:
                    - vacation_work_log_out_detail
            swagger_context:
                summary: Marks the VacationWorkLog as approved.
        markRejected:
            method: PUT
            route_name: api_vacation_work_log_mark_rejected
            normalization_context:
                groups:
                    - vacation_work_log_out_detail
            swagger_context:
                summary: Marks the VacationWorkLog as rejected.