App\Entity\Vacation:
    collectionOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - vacation_out_list
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - vacation_out_detail
    subresourceOperations:
        api_users_vacations_get_subresource:
            method: GET
            normalization_context:
                groups:
                    - vacation_out_list
