App\Entity\WorkMonth:
    attributes:
        filters:
            - search_filter.work_month
    collectionOperations:
        api_users_work_months_get_subresource:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
        get:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_detail
