App\Entity\WorkMonth:
    attributes:
        filters:
            - search_filter.work_month
    collectionOperations:
        specialApprovals:
            method: GET
            route_name: api_work_months_special_approvals
            normalization_context:
                groups:
                    - special_approvals_out_list
            swagger_context:
                summary: Retrieves the collection of special work logs which need to approved.
        recentSpecialApprovals:
            method: GET
            route_name: api_work_months_recent_special_approvals
            normalization_context:
                groups:
                    - special_approvals_out_list
            swagger_context:
                summary: Retrieves the collection of all special work logs which belongs to current and previous work month.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
            swagger_context:
                summary: Retrieves a WorkMonth resource without work logs.
        getWorkMonthDetail:
            method: GET
            route_name: api_work_months_detail
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Retrieves a WorkMonth resource with work logs.
        setWorkTimeCorrection:
            method: PUT
            route_name: api_work_months_set_work_time_correction
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Set work time correction of the WorkMont.
                parameters:
                    -   name: workTimeCorrection
                        description: 'Work time correction'
                        type: int
                        in: body
                        required: true
        markApproved:
            method: PUT
            route_name: api_work_months_mark_approved
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Marks the WorkMonth as approved.
        markWaitingForApproval:
            method: PUT
            route_name: api_work_months_mark_waiting_for_approval
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Marks the WorkMonth as waiting for approval.
    subresourceOperations:
        api_users_work_months_get_subresource:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
