App\Entity\WorkLog:
    collectionOperations:
        post:
            method: POST
            normalization_context:
                groups:
                    - work_log_out_detail
            denormalization_context:
                groups:
                    - work_log_in
    itemOperations:
        put:
            method: PUT
            normalization_context:
                groups:
                    - work_log_out_detail
            denormalization_context:
                groups:
                    - work_log_in
        delete:
            method: DELETE
        get:
            method: GET
            normalization_context:
                groups:
                    - work_log_out_detail
