App\Entity\WorkMonth:
    attributes:
        filters:
            - search_filter.work_month
    collectionOperations:
        api_users_work_months_get_subresource:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
        get:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_list
        specialApprovals:
            method: GET
            route_name: api_work_months_special_approvals
            normalization_context:
                groups:
                    - special_approvals_out_list
            swagger_context:
                summary: Retrieves the collection of special work logs which need to approved.
    itemOperations:
        get:
            method: GET
            normalization_context:
                groups:
                    - work_month_out_detail
        markApproved:
            method: PUT
            route_name: api_work_months_mark_approved
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Marks the WorkMonth as approved.
        markWaitingForApproval:
            method: PUT
            route_name: api_work_months_mark_waiting_for_approval
            normalization_context:
                groups:
                    - work_month_out_detail
            swagger_context:
                summary: Marks the WorkMonth as waiting for approval.