App\Entity\WorkHours:
    collectionOperations:
        api_users_work_hours_get_subresource:
            method: 'GET'
            normalization_context:
                groups:
                    - work_hours_out_list
        get:
            method: 'GET'
            normalization_context:
                groups:
                    - work_hours_out_list
    itemOperations:
        get:
            method: 'GET'
            normalization_context:
                groups:
                    - work_hours_out_detail
